#!/usr/bin/env python

import numpy as np
import argparse
import os, warnings, sys
with warnings.catch_warnings():
    warnings.filterwarnings("ignore", category=FutureWarning)
    import nibabel as nib

PRECISION= 17
np.set_printoptions(precision= PRECISION, suppress= True, floatmode= 'maxprec')

from bval_bvec_io import read_bvecs, read_bvals, bvec_scaling

def matrix_string(A):
    # A= np.array(A)
    
    A= str(A.tolist())
    A= A.replace(', ',',')
    A= A.replace('],[',') (')
    return '('+A[2:-2]+')'
    
def find_mf(F):

    FFT= F @ F.T
    lam, V= np.linalg.eig(FFT)
    FFTsqrt= V @ np.diag(np.sqrt(lam)) @ V.T
    R= FFTsqrt @ F

    # get rid of scaling, normalize each column
    R/=np.linalg.norm(R, axis=0)

    return R.T

def main():

    parser = argparse.ArgumentParser(description='NIFTI to NHDR conversion tool setting byteskip = -1')
    parser.add_argument('--nifti', type=str, required=True, help='nifti file')
    parser.add_argument('--bval', type=str, help='bval file')
    parser.add_argument('--bvec', type=str, help='bvec file')
    parser.add_argument('--nhdr', type=str, help='output nhdr file')

    args = parser.parse_args()

    if args.nifti.endswith('.gz'):
        encoding = 'gzip'
    elif args.nifti.endswith('.nii'):
        encoding = 'raw'
    else:
        raise ValueError('Invalid nifti file')

    img= nib.load(args.nifti)
    hdr= img.header

    if not args.nhdr:
        args.nhdr= os.path.abspath(args.nifti).split('.')[0]+'.nhdr'
    elif not args.nhdr.endswith('nhdr'):
        raise AttributeError('Output file must be nhdr')
    else:
        args.nhdr= os.path.abspath(args.nhdr)

    f= open(os.path.abspath(args.nhdr), 'w')
    console= sys.stdout
    sys.stdout= f

    dim= hdr['dim'][0]
    dtype= hdr.get_data_dtype()
    np_to_nrrd = {
        'int8': 'int8',
        'int16': 'short',
        'int32': 'int',
        'int64': 'longlong',
        'uint8': 'uchar',
        'uint16': 'ushort',
        'uint32': 'uint',
        'uint64': 'ulonglong',
        'float32': 'float',
        'float64': 'double'
        }

    print(f'NRRD0005\n# This nhdr file was generated by pnl.bwh.harvard.edu pipeline\n\
# See https://github.com/pnlbwh for more info\n\
# Complete NRRD file format specification at:\n\
# http://teem.sourceforge.net/nrrd/format.html\n\
type: {np_to_nrrd[dtype.name]}\ndimension: {dim}\nspace: right-anterior-superior')

    sizes= hdr['dim'][1:dim+1]
    print('sizes: {}'.format((' ').join(str(x) for x in sizes)))

    spc_dir= hdr.get_qform()[0:3,0:3]

    # most important key
    print('byteskip: -1')

    endian= 'little' if dtype.byteorder=='<' else 'big'
    print(f'endian: {endian}')
    print(f'encoding: {encoding}')
    print('space units: "mm" "mm" "mm"')

    spc_orig= hdr.get_qform()[0:3,3]
    print('space origin: ({})'.format((',').join(str(x) for x in spc_orig)))


    if dim==4:
        print(f'space directions: {matrix_string(spc_dir.T)} none')
        print('centerings: cell cell cell ???')
        print('kinds: space space space list')

        mf = find_mf(spc_dir)
        print(f'measurement frame: {matrix_string(mf)}')

        bvecs = read_bvecs(args.bvec, assumed_norm= False)
        bvals = read_bvals(args.bval)

        print('data file: ', args.nifti)
        print('modality:=DWMRI')

        b_max = max(bvals)
        print(f'DWMRI_b-value:={b_max}')
        for ind in range(len(bvals)):
            scaled_bvec = bvec_scaling(bvals[ind], bvecs[ind], b_max)
            print(f'DWMRI_gradient_{ind:04}:={scaled_bvec}')

    else:
        print(f'space directions: {matrix_string(spc_dir.T)}')
        print('centerings: cell cell cell')
        print('kinds: space space space')
        print('data file: ', args.nifti)
        
    f.close()
    sys.stdout= console


if __name__ == '__main__':
    main()
